"""Generate the current sedan's embedded header without changing its geometry."""
from pathlib import Path
import sys
import json
import math

root = Path(__file__).resolve().parent
mesh = json.loads((root / "sedan.json").read_text(), parse_int=lambda s: -0.0 if s == "-0" else int(s))
vertices, indices = mesh["vertices"], mesh["indices"]
materials = ["Paint", "Glass", "Rubber", "Chrome", "Headlight", "Taillight"]
assert mesh["format"] == 1 and len(vertices) <= 1024 and len(indices) <= 1536
assert len(indices) % 3 == 0 and all(0 <= i < len(vertices) for i in indices)
assert all(len(v) == 8 and all(math.isfinite(x) for x in v) for v in vertices)
assert all(0 <= v[6] < len(materials) and 0 <= v[7] <= 0xFFFFFF for v in vertices)

# Share only identical position/normal/material/colour vertices. Hard edges and
# every indexed triangle remain intact; this is not a lower-detail model.
original = vertices
vertices, remap, lookup = [], [], {}
for vertex in original:
    key = tuple(vertex)
    if key not in lookup:
        lookup[key] = len(vertices)
        vertices.append(vertex)
    remap.append(lookup[key])
indices = [remap[i] for i in indices]
assert all(vertices[indices[i]] == original[mesh["indices"][i]] for i in range(len(indices)))

def vector(values):
    # Nine significant digits round-trip the original single-precision values.
    def number(value):
        text = format(value, ".9g")
        return text + ("f" if "." in text or "e" in text else ".0f")
    return "{ " + ",".join(number(x) for x in values) + " }"

lines = ["#pragma once", '#include "DistantMesh.hpp"', "",
         "// Generated by resources/distant-car/generate.py from sedan.json.",
         "// Original sedan: metres, +Y forward, +Z up, Z=0 at tyre contact.",
         "namespace DistantCarMesh", "{", "    struct Mesh : Geometry", "    {",
         "        Mesh()", "        {", "            static const Vertex data[] =", "            {"]
for v in vertices:
    lines.append(f"                {{ {vector(v[:3])}, {vector(v[3:6])}, {materials[v[6]]}, 0x{v[7]:06X}u }},")
lines += ["            };", "            static const short triangles[] =", "            {"]
for start in range(0, len(indices), 18):
    lines.append("                " + ",".join(map(str, indices[start:start+18])) + ",")
lines += ["            };", "            for (const auto& vertex : data) vertices.push_back(vertex);",
          "            for (short index : triangles) indices.push_back(index);", "        }", "    };", "}", ""]
output = root.parent.parent / "source/DistantCarMesh.hpp"
generated = "\n".join(lines)
if "--check" in sys.argv:
    if output.read_text() != generated:
        raise SystemExit(f"{output.name} needs regeneration")
else:
    output.write_text(generated)
print(f"Embedded sedan: {len(vertices)} vertices, {len(indices)//3} triangles (unchanged model).")
