"""Bake the supplied boat mesh/texture into embedded vertex colours (requires Pillow)."""
from pathlib import Path
import sys
import math
import re
from PIL import Image

root = Path(__file__).resolve().parent
text = (root / "boat.mesh").read_text()
blocks = re.findall(r"Idx \d+\s*\{(.*?)\}\s*Verts \d+\s*\{(.*?)\}", text, re.S)
texture = Image.open(root / "boat.tga").convert("RGB")
triangles = set()
vertices = []

def sample(v):
    x = max(0, min(texture.width - 1, round(v[6] * (texture.width - 1))))
    y = max(0, min(texture.height - 1, round(v[7] * (texture.height - 1))))
    return texture.getpixel((x, y))

def midpoint(a, b):
    return [(x + y) * .5 for x, y in zip(a, b)]

def emit(a, b, c):
    # Deduplicate the overlapping hull copies, then subdivide once so the baked
    # texture preserves its hull/deck shading without a runtime texture resource.
    ab, bc, ca = midpoint(a, b), midpoint(b, c), midpoint(c, a)
    for tri in [(a, ab, ca), (ab, b, bc), (ca, bc, c), (ab, bc, ca)]:
        for v in tri:
            n = math.sqrt(sum(x*x for x in v[3:6]))
            assert n > .001
            p = (-v[0], -v[1] - 2.23809433, v[2])
            normal = (-v[3]/n, -v[4]/n, v[5]/n)
            vertices.append((p, normal, sample(v)))

for indices, block in blocks:
    source = []
    for line in block.strip().splitlines():
        parts = [list(map(float, part.split())) for part in line.split("/")]
        source.append(parts[0] + parts[1] + parts[4])
    ids = list(map(int, indices.split()))
    for i in range(0, len(ids), 3):
        a, b, c = [source[j] for j in ids[i:i+3]]
        key = tuple(sorted(tuple(round(x, 4) for x in v[:3]) for v in (a,b,c)))
        if key in triangles:
            continue
        triangles.add(key)
        u, v = [b[j]-a[j] for j in range(3)], [c[j]-a[j] for j in range(3)]
        cross = (u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0])
        if sum(cross[j]*(a[j+3]+b[j+3]+c[j+3]) for j in range(3)) < 0:
            b,c = c,b
        emit(a,b,c)

assert len(vertices) <= 1024
lines = ["#pragma once", '#include "DistantMesh.hpp"', "",
         "// Generated by resources/distant-boat/generate.py from the supplied model.",
         "// Metres; +Y is the bow, Z=0 is the waterline. No runtime asset loading.",
         "namespace DistantBoatMesh", "{", "    struct Mesh : DistantCarMesh::Geometry", "    {",
         "        Mesh()", "        {", "            static const DistantCarMesh::Vertex data[] =", "            {"]
for p,n,rgb in vertices:
    vec = lambda xyz: "{ " + ",".join(f"{x:.6f}f" for x in xyz) + " }"
    color = (rgb[0]<<16) | (rgb[1]<<8) | rgb[2]
    lines.append(f"                {{ {vec(p)}, {vec(n)}, DistantCarMesh::BoatHull, 0x{color:06X}u }},")
lines += ["            };", "            for (const auto& vertex : data)", "            {",
          "                indices.push_back(static_cast<short>(vertices.size()));", "                vertices.push_back(vertex);",
          "            }", "        }", "    };", "}", ""]
output = root.parent.parent / "source/DistantBoatMesh.hpp"
generated = "\n".join(lines)
if "--check" in sys.argv:
    if output.read_text() != generated:
        raise SystemExit(f"{output.name} needs regeneration")
else:
    output.write_text(generated)
print(f"Embedded boat: {len(triangles)} source triangles, {len(vertices)//3} baked triangles.")
