"""Generate the embedded III water network. Optional validation uses stock waterpro.dat."""
import argparse, json, math, struct
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]

def network():
    data = json.loads((Path(__file__).with_name('routes.json')).read_text())
    points, links, ids = [], set(), {}
    def node(p):
        p = tuple(round(v, 4) for v in p)
        if p not in ids:
            ids[p] = len(points)
            points.append(p)
        return ids[p]
    for route in data['routes']:
        path = route['points']
        for a, b in zip(path, path[1:] + path[:1]):
            # Canonical orientation makes shared channel subdivisions identical.
            a, b = sorted((a, b))
            steps = math.ceil(math.dist(a, b) / 220)
            last = node(a)
            for i in range(1, steps + 1):
                cur = node([a[k] + (b[k] - a[k]) * i / steps for k in range(2)])
                links.add(tuple(sorted((last, cur))))
                last = cur
    return points, sorted(links)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--water-map', type=Path)
    args = parser.parse_args()
    points, links = network()
    if args.water_map:
        raw = args.water_map.read_bytes()
        assert len(raw) == 21444
        levels = struct.unpack_from('<48f', raw, 4)
        mask = struct.unpack_from('<16384b', raw, 4 + 192 + 768 + 4096)
        def wet(x, y):
            ix, iy = int((x + 2048) // 32), int((y + 2048) // 32)
            if not (0 <= ix < 128 and 0 <= iy < 128): return False
            i = mask[ix * 128 + iy]
            return 0 <= i < 48 and abs(levels[i]) < .01
        errors = []
        for a, b in links:
            p, q = points[a], points[b]
            for i in range(math.ceil(math.dist(p, q) / 5) + 1):
                t = min(1, i * 5 / math.dist(p, q))
                x, y = (p[k] + (q[k] - p[k]) * t for k in range(2))
                if any(not wet(x + 40 * math.cos(n * math.pi / 4), y + 40 * math.sin(n * math.pi / 4)) for n in range(8)):
                    errors.append((a,b,round(x),round(y))); break
        if errors:
            raise SystemExit(f'Coast clearance failures: {errors}')
        print('Centre lines have 40m sea-water clearance.')
    neighbours = [[] for _ in points]
    for a,b in links:
        neighbours[a].append(b);neighbours[b].append(a)
    assert all(2 <= len(n) <= 4 for n in neighbours)
    out = ['#pragma once', '#include <array>', '', '// Generated by resources/iii-water-paths/generate.py. No runtime asset files.', 'namespace IIIWaterPaths', '{', '    struct Node', '    {', '        float x, y;', '        std::array<unsigned, 4> links;', '        unsigned count;', '    };', f'    inline constexpr std::array<Node, {len(points)}> Nodes =', '    {{']
    for p,ns in zip(points,neighbours):
        nums = ', '.join(map(str,ns+[0]*(4-len(ns))))
        out.append(f'        {{ {p[0]:.4f}f, {p[1]:.4f}f, {{ {nums} }}, {len(ns)} }},')
    out += ['    }};', '}', '']
    (ROOT/'source/IIILodLights/WaterPaths.hpp').write_text('\n'.join(out))
    print(f'{len(points)} nodes, {len(links)} links')
if __name__ == '__main__': main()
